[package]
name = "aoc-2019-9"
version = "0.1.0"
authors = ["Dominic Bowden <tedle@blon.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.intcode]
path = "../intcode"
